---
docker_opts: ''
docker_create_group: true
docker_service_start_timeout: ''    # use system default value

##### ---
# Want to advertise the tcp port? Enable below.
# To enable tcp you must set :
#   - `docker_listen_tcp = True`
#   - uncomment `docker_opts` or provide it as a override
#
# Note:
#   By setting `-H` opt for docker, it will no longer be listenting
#   on the socket. You cannot have both. You must choose socket `-d`
#   or tcp `-H`.
#
docker_listen_tcp: True
docker_listen_port: 2375
# docker_opts: '"-H tcp://{{ansible_eth1.ipv4.address}}:{{docker_listen_port}}"'
##### ---