---
docker_create_group: true
docker_service_start_timeout: ''    # use system default value

docker_listen_tcp: True
docker_listen_port: 2375
docker_opts: '"-H tcp://{{ansible_eth1.ipv4.address}}:{{docker_listen_port}}"'