---

- name: Consul is running
  docker:
    name: consul
    hostname: "{{ hostname }}"
    image: progrium/consul:latest
    ports:
      - 8300:8300
      - 8301:8301
      - 8301:8301/udp
      - 8302:8302
      - 8302:8302/udp
      - 8400:8400
      - 8500:8500
      - 8600:53/udp
      - 53:53/udp
    docker_url: "{{ ip }}:2375"
    command: -server -advertise {{ ip }} -bootstrap -log-level debug
  when: consul_master_ip is not defined
  tags: [consul]

- name: Consul is running
  docker:
    name: consul
    hostname: "{{ hostname }}"
    image: progrium/consul:latest
    ports:
      - 8300:8300
      - 8301:8301
      - 8301:8301/udp
      - 8302:8302
      - 8302:8302/udp
      - 8400:8400
      - 8500:8500
      - 8600:53/udp
      - 53:53/udp
    docker_url: "{{ ip }}:2375"
    command: -server -advertise {{ ip }} -join {{ consul_master_ip }} -log-level debug
  when: consul_master_ip is defined
  tags: [consul]

- name: Registrator is running
  docker:
    name: registrator
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    hostname: "{{ hostname }}"
    image: gliderlabs/registrator
    docker_url: "{{ ip }}:2375"
    command: -ip {{ ip }} consul://{{ ip }}:8500
  tags: [consul]