- name: Compose template is present
  template:
    src: "docker-compose.yml.j2"
    dest: "{{ compose_dir }}/docker-compose.yml.ctmpl"
  register: result
  tags: [service]

- name: Service is running
  shell: docker-compose up -d
  args:
    chdir: "{{ compose_dir }}"
  environment:
    DOCKER_HOST: tcp://0.0.0.0:2375
  register: result
  tags: [service]