- name: Install dependencies packages.
  apt: name={{ item }} state=present
  with_items:
    - python-pip
    - python-virtualenv
  tags: [docker]

- name: Add Docker repository key
  apt_key:
    id: "{{ apt_key_sig }}"
    url: "{{ apt_key_url }}"
    state: present
  register: add_repository_key
  ignore_errors: true
  tags: [docker]

- name: Alternative | Add Docker repository key
  shell: curl -sSL https://get.docker.com/gpg | sudo apt-key add -
  when: add_repository_key|failed
  tags: [docker]

- name: Add Docker repository and update apt cache
  apt_repository:
    repo: "{{ apt_repository }}"
    update_cache: yes
    state: present
  tags: [docker]

- name: Install (or update) docker package
  apt:
    name: "{{ docker_pkg_name }}"
    state: "{{ 'latest' if update_docker_package else 'present' }}"
    update_cache: yes
    cache_valid_time: "{{ docker_apt_cache_valid_time }}"
  tags: [docker]

#- name: Run installer
#  command: '/bin/sh /tmp/docker_install.sh'
#  when: get_docker|changed and docker_installed != "0"
#  tags: [docker]

- name: Obsolete Docker init.d service is removed
  file:
    dest: /etc/init.d/docker
    state: absent
  tags: [docker]

- name: Configuration is present
  template: src=docker-defaults.j2 dest=/etc/default/docker
  register: config_result
  when: not swarm_master is defined
  tags: [docker]

- name: Service is restarted
  service:
    name=docker
    state=restarted
#  when: config_result|changed
  tags: [docker]

#- name: Change ufw forward policy to ACCEPT
#  command: sed -i 's/DEFAULT_FORWARD_POLICY="DROP"/DEFAULT_FORWARD_POLICY="ACCEPT"/g' /etc/default/ufw
#  when: docker_listen_tcp == True
#  tags: [docker]
#
#- name: Reload ufw
#  command: ufw reload
#  when: docker_listen_tcp == True
#  tags: [docker]
#
#- name: Allow incomming tcp traffic on {{docker_listen_port}}
#  command: ufw allow {{docker_listen_port}}/tcp
#  when: docker_listen_tcp == True
#  tags: [docker]
#
#- name: Check if /etc/init exists
#  stat: path=/etc/init/
#  register: etc_init
#  tags: [docker]

#- name: Docker upstart default config file
#  template: src=docker-defaults.j2 dest=/etc/default/docker
#  when: etc_init.stat.exists == true
#  notify:
#    - Restart Docker
#  tags: [docker]
#
#- name: Check if systemd exists
#  stat: path=/usr/lib/systemd/system/
#  register: systemd_check
#  tags: [docker]

#- name: Docker systemd default config file
#  template: src=docker-sysconfig.j2 dest=/etc/sysconfig/docker
#  when: systemd_check.stat.exists == true
#  notify:
#    - Restart Docker
#  tags: [docker]

#- name: Docker systemd file
#  template: src=docker-service.j2 dest=/lib/systemd/system/docker.service backup=yes
#  when: systemd_check.stat.exists == true
#  notify:
#    - Restart Docker
#  tags: [docker]

- name: Python-pip is present
  apt:
    name: python-pip
    state: present
  tags: [docker]

- name: Docker-py is present
  pip: name=docker-py version=0.4.0 state=present
  tags: [docker]