---

- name: Install dependencies packages.
  apt: name={{ item }} state=present
  with_items:
    - python-pip
    - python-virtualenv
  tags: [docker]

- name: Add Docker repository key
  apt_key:
    id: "{{ apt_key_sig }}"
    url: "{{ apt_key_url }}"
    state: present
  register: add_repository_key
  ignore_errors: true
  tags: [docker]

- name: Alternative | Add Docker repository key
  shell: curl -sSL https://get.docker.com/gpg | sudo apt-key add -
  when: add_repository_key|failed
  tags: [docker]

- name: Add Docker repository and update apt cache
  apt_repository:
    repo: "{{ apt_repository }}"
    update_cache: yes
    state: present
  tags: [docker]

- name: Install (or update) docker package
  apt:
    name: "{{ docker_pkg_name }}"
    state: "{{ 'latest' if update_docker_package else 'present' }}"
    update_cache: yes
    cache_valid_time: "{{ docker_apt_cache_valid_time }}"
  tags: [docker]

- name: Obsolete Docker init.d service is removed
  file:
    dest: /etc/init.d/docker
    state: absent
  tags: [docker]

- name: Configuration is present
  template: src=docker-defaults.j2 dest=/etc/default/docker
  register: config_result
  when: not swarm_master is defined
  tags: [docker]

- name: Service is restarted
  service:
    name=docker
    state=restarted
  when: config_result|changed
  tags: [docker]

- name: Python-pip is present
  apt:
    name: python-pip
    state: present
  tags: [docker]

- name: Docker-py is present
  pip: name=docker-py version=0.4.0 state=present
  tags: [docker]