- name: Directories are present
  file:
    dest: "{{ item.dest_dir }}"
    state: directory
  with_items: files
  tags: [proxy]

- name: Files are present
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest_dir }}/{{ item.dest_file }}"
    mode: "{{ item.mode }}"
  with_items: files
  tags: [proxy]

- name: Proxy is running
  docker:
    name: proxy
    image: 1science/nginx:consul
    ports:
      - 80:80
    env:
      CONSUL_URL: {{ ip }}:8500
      SERVICE_NAME: nginx
    volumes:
      - /data/apllication/nginx:/etc/consul-template:ro
  tags: [proxy]

#nginx:
#  image: 1science/nginx:consul
#  links:
#    - consul
#  ports:
#    - 80:80
#  volumes:
#    - ./nginx/consul-template:/etc/consul-template:ro
#  environment:
#    CONSUL_URL: 192.168.50.15:8500
#    SERVICE_NAME: nginx

#- name: Check or build image
#  docker_image: path="/path/to/build/dir" name="my/proxy" state=present