---

- name: Directories are present
  file:
    dest: "{{ item.dest_dir }}"
    state: directory
  with_items: files
  tags: [proxy]

- name: Files are present
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest_dir }}/{{ item.dest_file }}"
    mode: "{{ item.mode }}"
  with_items: files
  tags: [proxy]

- name: Proxy is running
  docker:
    name: proxy
    image: 1science/nginx:consul
    ports:
      - 80:80
    env:
      CONSUL_URL: "{{ ip }}:8500"
      SERVICE_NAME: nginx
    volumes:
      - /data/application/nginx:/etc/consul-template:ro
  tags: [proxy]